name: on demand
on: 
  workflow_dispatch:
    inputs:
      firstName:
        description: 'Choisissez un prénom'
        required: true
        default: 'john'
        type: string
      
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print  
        run: echo "Bonjour ${{ inputs.firstName }}"
      
